GET http://localhost/wp-json/university/v1/search?term=lorem
Content-Type: application/json

###

GET http://localhost/wp-json/wp/v2/posts?per_page=3&page=2
Content-Type: application/json

###

GET http://localhost/wp-json/wp/v2/professor?_fields=id,title,_links,_embedded&_embed=wp:featuredmedia
Content-Type: application/json
